-------------------------------------------------------------------------------
-- Copyright Peter Beard, Licensed under the GPLv2, see LICENSE for details.
--
-- Problem #2
-- 
-- Each new term in the Fibonacci sequence is generated by adding the previous
-- two terms. By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed
-- four million, find the sum of the even-valued terms.
-------------------------------------------------------------------------------

with Ada.Text_IO; use Ada.Text_IO;

procedure Problem002 is
    sum     : Integer  := 2;
    a       : Integer  := 1;
    b       : Integer  := 2;

    FIB_MAX : Constant := 4_000_000;
begin
    while a + b < FIB_MAX loop
        b := a + b;
        a := b - a;
        if b mod 2 = 0 then
            sum := sum + b;
        end if;
    end loop;

    Put_Line("The sum of all even Fibonacci numbers below" & Integer'Image(FIB_MAX) & " is" & Integer'Image(sum));
end Problem002;
