/*
 * Copyright 2016 Peter Beard
 * Distributed under the GNU GPL v2. For full terms, see the LICENSE file.
 *
 * Problem #2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two
 * terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */
#include <stdio.h>

int main()
{
    int a = 1, b = 1;
    int sum = 0;
    while(b < 4000000)
    {
        int tmp = a;
        a = b;
        b += tmp;
        if(b % 2 == 0)
            sum += b;
    }
    printf("The sum of the even terms of the Fibonacci sequence less than 4,000,000 is %d.\n", sum);
}
