/*
 * Copyright 2016 Peter Beard
 * Distributed under the GNU GPL v2. For full terms, see the LICENSE file.
 *
 * Problem #12
 *
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
 * ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *      1: 1
 *      3: 1,3
 *      6: 1,2,3,6
 *      10: 1,2,5,10
 *      15: 1,3,5,15
 *      21: 1,3,7,21
 *      28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred
 * divisors?
 */
#include <stdio.h>

// Count the number of factors of some integer n -- includes 1 and n
int num_factors(int n)
{
    // 1 and n are the trivial factors
    int count = 2;
    int f = 2;
    while(f * f <= n)
    {
        if(n % f == 0)
            count += 2;
        // Don't double-count the square root
        if(f * f == n)
            count--;
        f++;
    }
    return count;
}

int main()
{
    const int max_factors = 500;
    int n = 1;
    int triangle = 1;
    while(1)
    {
        n++;
        triangle += n;
        if(num_factors(triangle) > max_factors)
        {
            break;
        }
    }
    printf("The first triangle number to have over %d factors is %d.\n", max_factors, triangle);
}
