;; Copyright 2017 Peter Beard
;; Distributed under the GNU GPL v2. For full terms, see the LICENSE file.
;;
;; Problem #2
;;
;; Each new term in the Fibonacci sequence is generated by adding the previous two
;; terms. By starting with 1 and 2, the first 10 terms will be:
;; 
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; 
;; By considering the terms in the Fibonacci sequence whose values do not exceed
;; four million, find the sum of the even-valued terms.

(ns problem-002.core
  (:gen-class))

(defn fibs-up-to
  "Calculate the Fibonacci sequence up to some maximum value"
  [a b maximum]
  (if (> a maximum)
    []
    (into [a] (fibs-up-to b (+ a b) maximum))))

(defn solution
  "Solution for problem 2"
  []
  (reduce + (filter even? (fibs-up-to 1 2 4000000))))

(defn -main
  "Print the solution"
  [& args]
  (println "The sum of the even terms of the Fibonacci sequence less than 4,000,000 is" (solution)))
